apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kubernetes-basic-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: kubernetes.rules
      rules:

        - alert: TestImagePullBackOff
          expr: kube_pod_container_status_waiting_reason{reason=~"ImagePullBackOff|ErrImagePull"} == 1
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Pod {{ $labels.pod }} has an image pull error"
            description: "Container {{ $labels.container }} in pod {{ $labels.pod }} (namespace {{ $labels.namespace }}) can't pull its image."
        
        - alert: KubernetesNodeNotReady
          expr: kube_node_status_condition{
                  condition="Ready",
                  status="true"
                } == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Kubernetes node is not ready"
            description: "Node {{ $labels.node }} has been NotReady for more than 5 minutes."

        - alert: KubernetesPodCrashLooping
          expr: increase(
                  kube_pod_container_status_restarts_total[15m]
                ) > 3
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Pod is restarting repeatedly"
            description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is restarting repeatedly."

        - alert: KubernetesDeploymentReplicasMismatch
          expr: kube_deployment_spec_replicas
                != kube_deployment_status_available_replicas
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Deployment replicas mismatch"
            description: "Deployment {{ $labels.namespace }}/{{ $labels.deployment }} does not have the desired available replicas."
