grafana:
  enabled: true
  replicas: 1
  persistence:
    enabled: true
    storageClassName: gp3
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "kubernetes"
          orgId: 1
          folder: "Kubernetes"
          type: file
          disableDeletion: false
          editable: false
          options:
            path: /var/lib/grafana/dashboards/kubernetes
  dashboards:
    kubernetes:
      kubernetes-cluster:
        gnetId: 15757
        revision: 37
        datasource: Prometheus

      kubernetes-nodes:
        gnetId: 1860
        revision: 37
        datasource: Prometheus

      kubernetes-pods:
        gnetId: 6417
        revision: 1
        datasource: Prometheus
prometheus:
  enabled: true

  prometheusSpec:
    retention: 15d

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi

    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 2Gi

alertmanager:
  enabled: true

  alertmanagerSpec:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
