apiVersion: v1
kind: Pod
metadata:
  name: test-ebs-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: ebs-storage
          mountPath: /data
  volumes:
    - name: ebs-storage
      persistentVolumeClaim:
        claimName: test-ebs-pvc
