apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloword-argocd
  namespace: argocd
spec:
  project:
    helloword-project
  source:
    repoURL: https://github.com/meghraj8788/deployment_simple_application.git
    targetRevision: main
    path: k8s/

  destination:
    server: https://kubernetes.default.svc
    namespace: helloword
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
